//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddInsLibrary.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AddInsLibrary.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   (EN)添付されたファイルにはS秘の情報が含まれているため外部に送信できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msg_err_includingS {
            get {
                return ResourceManager.GetString("msg_err_includingS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (EN)保存を許可されていないファイルが開かれています。対象ファイルを閉じてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msg_err_lock_file {
            get {
                return ResourceManager.GetString("msg_err_lock_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (EN)送信許可権限がある方がCC欄に含まれていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msg_err_not_authorization {
            get {
                return ResourceManager.GetString("msg_err_not_authorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (EN)添付されたファイルには機密区分が登録されていないものが含まれているため外部に送信できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msg_err_not_stamp {
            get {
                return ResourceManager.GetString("msg_err_not_stamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (EN)プロパティ情報の読み込みが失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msg_err_properties_read {
            get {
                return ResourceManager.GetString("msg_err_properties_read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (EN)ファイルプロパティの設定が失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msg_err_properties_write {
            get {
                return ResourceManager.GetString("msg_err_properties_write", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (EN)共通設定ファイルの読み込みに失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msg_err_read_common_file {
            get {
                return ResourceManager.GetString("msg_err_read_common_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (EN)スタンプ貼付け処理が失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msg_err_stamp_paste {
            get {
                return ResourceManager.GetString("msg_err_stamp_paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (EN)添付ファイルをZIP化して送信しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msg_info_zip_send {
            get {
                return ResourceManager.GetString("msg_info_zip_send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (EN)添付ファイルをZIP化しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msg_qst_create_zip {
            get {
                return ResourceManager.GetString("msg_qst_create_zip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (EN)添付されたファイルには機密情報が含まれているため、送信するには事前に上長の許可が必要です。送信しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msg_qst_send_authorization {
            get {
                return ResourceManager.GetString("msg_qst_send_authorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (EN)添付ファイルの送信を許可した上長がCC欄に含まれている場合は送信を、含まれていない場合は許可者選択を、クリックして下さい。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msg_qst_send_check {
            get {
                return ResourceManager.GetString("msg_qst_send_check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (EN)このファイルは既に機密区分が登録されています。選択した内容で上書きしますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msg_qst_stamp_orverwrite {
            get {
                return ResourceManager.GetString("msg_qst_stamp_orverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (EN)指定された場所には、S秘・A秘のファイルを保管する事ができません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msg_warning_save_not_secure {
            get {
                return ResourceManager.GetString("msg_warning_save_not_secure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (EN)キャンセル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgCancel {
            get {
                return ResourceManager.GetString("msgCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (EN)キャンセルボタン押下処理でエラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgCancelButtonError {
            get {
                return ResourceManager.GetString("msgCancelButtonError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (EN)CCボタン押下処理でエラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgCCButtonError {
            get {
                return ResourceManager.GetString("msgCCButtonError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (EN)閉じるボタン押下処理でエラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgCloseButtonError {
            get {
                return ResourceManager.GetString("msgCloseButtonError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (EN)共通設定ファイルで設定していない項目があります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgCommonSettingError {
            get {
                return ResourceManager.GetString("msgCommonSettingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (EN)確認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgConfirm {
            get {
                return ResourceManager.GetString("msgConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (EN)標準機密区分 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgDefaultSecure {
            get {
                return ResourceManager.GetString("msgDefaultSecure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (EN)エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgError {
            get {
                return ResourceManager.GetString("msgError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to read document path in common setting file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgFailedReadDocumentPath {
            get {
                return ResourceManager.GetString("msgFailedReadDocumentPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (EN)最終版 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgFinal {
            get {
                return ResourceManager.GetString("msgFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (EN)セキュアフォルダリスト に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgFolderList {
            get {
                return ResourceManager.GetString("msgFolderList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (EN)GCP機密文書(SA秘)一覧表の表示に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgGCPListError {
            get {
                return ResourceManager.GetString("msgGCPListError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (EN)GCP機密文書(SA秘)一覧表を開けませんでした。共通設定ファイルの文書パスを確認してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgGCPListPathCheck {
            get {
                return ResourceManager.GetString("msgGCPListPathCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (EN)文書のローカルパス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgLocalPath {
            get {
                return ResourceManager.GetString("msgLocalPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (EN)事業所コード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgOfficeCode {
            get {
                return ResourceManager.GetString("msgOfficeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (EN)OKボタン押下処理でエラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgOKButtonError {
            get {
                return ResourceManager.GetString("msgOKButtonError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (EN)エラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgOutputError {
            get {
                return ResourceManager.GetString("msgOutputError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (EN)メールの添付ファイルを展開するパスワードは以下の通りです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgPasswordMail {
            get {
                return ResourceManager.GetString("msgPasswordMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (EN)パスワードメール作成処理に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgPasswordMailError {
            get {
                return ResourceManager.GetString("msgPasswordMailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (EN)[パスワード通知] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgPasswordNotification {
            get {
                return ResourceManager.GetString("msgPasswordNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (EN)パスワード付きのzipを検知しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgPasswordZip {
            get {
                return ResourceManager.GetString("msgPasswordZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (EN)許可者要否のチェック処理で失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgPermitError {
            get {
                return ResourceManager.GetString("msgPermitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (EN)許可者選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgPermitSelect {
            get {
                return ResourceManager.GetString("msgPermitSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (EN)許可者選択ボタン押下処理でエラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgPermitSelectButtonError {
            get {
                return ResourceManager.GetString("msgPermitSelectButtonError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (EN)許可者を選択してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgPermitSelection {
            get {
                return ResourceManager.GetString("msgPermitSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (EN)登録ボタン押下処理でエラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgRegistButtonError {
            get {
                return ResourceManager.GetString("msgRegistButtonError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (EN)検索ボタン押下処理でエラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgSearchButtonError {
            get {
                return ResourceManager.GetString("msgSearchButtonError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (EN)機密区分ボタン押下処理でエラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgSecrecyButtonError {
            get {
                return ResourceManager.GetString("msgSecrecyButtonError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (EN)送信 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgSend {
            get {
                return ResourceManager.GetString("msgSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (EN)送信可否のチェック処理で失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgSendError {
            get {
                return ResourceManager.GetString("msgSendError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (EN)文書のサーバーパス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgServerPath {
            get {
                return ResourceManager.GetString("msgServerPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (EN)言語設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgSettingLanguage {
            get {
                return ResourceManager.GetString("msgSettingLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (EN)添付ファイルの一時フォルダ作成処理で失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgTempCreateError {
            get {
                return ResourceManager.GetString("msgTempCreateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (EN)添付ファイルのZIP処理で失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgTempZipError {
            get {
                return ResourceManager.GetString("msgTempZipError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (EN)zip一時解凍先 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgTempZipPath {
            get {
                return ResourceManager.GetString("msgTempZipPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (EN)解凍できないzipを検知しました。添付ファイルを見直してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgUnZipError {
            get {
                return ResourceManager.GetString("msgUnZipError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (EN)表示切替ボタン押下処理でエラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgViewChangeError {
            get {
                return ResourceManager.GetString("msgViewChangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   c:\tmp\secure に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string path_secure_folder {
            get {
                return ResourceManager.GetString("path_secure_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap StampA {
            get {
                object obj = ResourceManager.GetObject("StampA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap StampB {
            get {
                object obj = ResourceManager.GetObject("StampB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   OFF に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StampDisplay_OFF {
            get {
                return ResourceManager.GetString("StampDisplay_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ON に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StampDisplay_ON {
            get {
                return ResourceManager.GetString("StampDisplay_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap StampS {
            get {
                object obj = ResourceManager.GetObject("StampS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   許可者の選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string txt_Form_Title {
            get {
                return ResourceManager.GetString("txt_Form_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type A に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string txt_SecrecyA {
            get {
                return ResourceManager.GetString("txt_SecrecyA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type B に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string txt_SecrecyB {
            get {
                return ResourceManager.GetString("txt_SecrecyB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type None に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string txt_SecrecyNone {
            get {
                return ResourceManager.GetString("txt_SecrecyNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type S に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string txt_SecrecyS {
            get {
                return ResourceManager.GetString("txt_SecrecyS", resourceCulture);
            }
        }
    }
}
